### ISSUE TITLE
Library Problems

### ISSUE THREAD

**Issue by MrPeterJin** [WonderLandxD/sdpc-for-python#2]
Hi,

Appreciate for your solution towards .sdpc pathology slides. However, when I use your package, it raised the following error:

```
OSError: libDecodeHevc.so: cannot open shared object file: No such file or directory
```

I can't find any related information of this library file on Google. Can you resolve it?

Regards.

**Comment by WonderLandxD** [comment]
Thanks for your feedback.

It seems to be caused by missing **LD_LIBRARY_PATH** of _libDecodeHevc.so_ in the Linux system. You can solve it by adding 2 environment variables. The steps are as follows:

1. Find the path of _libDecodeHevc.so_ in the terminal
```
locate libDecodeHevc.so
```
You can see the absolute path where the file is located. For example, `/xxx/miniconda3/lib/python3.9/site-packages/sdpc/so/libDecodeHevc.so` in Miniconda. The following steps are replaced by `/ABSOLUTE_PATH/so/libDecodeHevc.so`, you need to replace ABSOULUTE_PATH with your own corresponding path.

2. Add the **_so_** folder path and the **_ffmpeg_** folder path to the environment variable

Edit ~/.bashrc.
```
vim ~/.bashrc
```
Add two environment variables on the last line.
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/ABSOLUTE_PATH/so/:/ABSOLUTE_PATH/so/ffmpeg/
```
make variables work
```
source ~/.bashrc
```
Once done, the sdpc library is ready to use. Hope this will help you.

**Comment by MrPeterJin** [comment]
It works! Thank you. 
May be you can add this info to the README.md as a troubleshooting part? It would benefit others.

**Comment by mingkai-zheng** [comment]
Hello, since I'm currently operating on an HPC server where I do not have the sudo permission, I cannot download the locate command. I'm wondering where libDecodeHevc.so is usually placed. And if there is no such file, which package do I need to install to obtain this file? Thank you so much !

**Comment by MrPeterJin** [comment]
> Hello, since I'm currently operating on an HPC server where I do not have the sudo permission, I cannot download the locate command. I'm wondering where libDecodeHevc.so is usually placed. And if there is no such file, which package do I need to install to obtain this file? Thank you so much !

Hi, are you installing it with pip in a conda environment? If so, maybe you can check in your-anaconda-folder/envs/your-env/lib/your-python/site-packages/sdpc/so

**Comment by mingkai-zheng** [comment]
> > Hello, since I'm currently operating on an HPC server where I do not have the sudo permission, I cannot download the locate command. I'm wondering where libDecodeHevc.so is usually placed. And if there is no such file, which package do I need to install to obtain this file? Thank you so much !
> 
> Hi, are you installing it with pip in a conda environment? If so, maybe you can check in `your-anaconda-folder/envs/your-env/lib/your-python/site-packages/sdpc/so`

I have successfully import the sdpc library, Thank you so much !

**Comment by zhaolei4383** [comment]
However, this isn't a perfect solution. Adding variables in bashrc can't work with jupyter notebook. Each of my friends has the same problem. Is this a bug that needs to be fixed?
