### ISSUE TITLE
total_num calculate

### ISSUE THREAD

**Issue by lingxitong** [WonderLandxD/sdpc-for-python#9]
hello,when calculating the total_num of the patches,I think the total_num of the patches is only related to the "patch_level" and "tile_size" which can be set as the super parameters.However,in the "cut_patches.py" ,total_num seems also related to the thumbnail_level?the thumbnail_level is a super parameter which decision the size of the thumbnail.png.

**Comment by WonderLandxD** [comment]
Hello, thank you for your advice. Indeed, total_num should not have anything to do with thumbnai_level. However, this does not affect the number of patches cut out. 
There are some other bugs that need to be fixed in the currently uploaded version, and we will solve these problems in the next version.
